LaBonneFemme/config/routes.rb
Rails.application.routes.draw do
  resources :women
  root "homes#index"
  get 'homes', to: "homes#index"
  get '/search', to: 'women#search', as: 'search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

LaBonneFemme/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

LaBonneFemme/app/models/woman.rb
class Woman < ApplicationRecord


  validates :name, presence:  true
  validates :surname, presence: true
  validates :age, presence: true
  validates :NumberPhone, presence: true

end

LaBonneFemme/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

LaBonneFemme/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

LaBonneFemme/app/controllers/women_controller.rb
class WomenController < ApplicationController


  def index
    @women = Woman.all
  end

  def show
    @woman = Woman.find(params[:id])
  end

  def search
    women = Woman.all
    search = params
    @women = []


    eyes = search[:color_eyes]
    hair = search[:color_hair]
    age = search[:age].to_i

    puts age

    if age == 0
      redirect_to root_path
    end

    women.each  do |elem|  #add in the array women_sort each woman'announce who correspond to the criteria

      if (elem[:color_eyes] == eyes || eyes == "toutes")  && ( elem[:color_hair] == hair || hair == "toutes" ) && (elem[:age] > age && elem[:age] < age + 10)
        @women << elem
      end
    end


  end

  def new
    @woman = Woman.new
  end

  def create
    @woman = Woman.new(params_woman)

    if @woman.save #save in database if only the form is correct
      if $flag
        $flag = false
      end
      redirect_to root_path, success: "Nouvelle annonce crée"
    else
      render 'new'
    end

  end

  private

  def params_woman
    params.require(:woman).permit(:name, :surname, :age, :NumberPhone,:color_eyes, :color_hair, :description)
  end
end

LaBonneFemme/app/helpers/application_helper.rb
module ApplicationHelper
end

LaBonneFemme/app/helpers/homes_helper.rb
module HomesHelper
end

LaBonneFemme/app/helpers/women_helper.rb
module WomenHelper
end

LaBonneFemme/app/views/application/_print_announces.html.erb
<% @women.each do |woman| %>
  <div class="card text-dark bg-info mb-3" style="max-width: 40%;margin-left: 30%">
    <div class="card-header text-center"><h3><b><%= woman.name+" "+woman.surname%></b></h3></div>
    <div class="card-body">
      <h4 class="card-title"><%= woman.age.to_s+" ans : "+woman.color_hair+" aux yeux "+woman.color_eyes%></h4>
      <h5>Contact : <%= woman.NumberPhone %></h5>
      <p class="card-text"><%= woman.description %></p>
    </div>
  </div>
<% end %>

LaBonneFemme/app/views/homes/index.html.erb
<div class="card border-success mb-6" style="max-width: 40%;margin-left: 30%">
  <div class="card-header bg-transparent border-success text-center" style="border-color :#fec5d9">Trouver la Femme de vos rêves</div>
  <div class="card-body text-success">
    <%= form_with model: @woman , url: search_path, method: :get do |form|%>

      <p>
        <%= form.label :color_eyes, "couleur des yeux : " %>
        <%= form.select :color_eyes, ["toutes", "bleus", "marrons", "noirs", "verts"] %>
      </p>

      <p>
        <%= form.label :color_hair, "couleur des cheveux :" %>
        <%= form.select :color_hair, ["toutes", "rousse", "blonde", "chataigne", "brune"] %>
      </p>


      <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
          <div class="card">
            <img src="<%= image_path("20.jpeg") %>" class="card-img" alt="...">
            <div class="card-body">
              <h5 class="card-title">20 à 30ans</h5>
              <div class="text text-center">
                <%= form.radio_button :age, 20 %>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card">
            <img src="<%= image_path("30.jpeg") %>" class="card-img" alt="...">
            <div class="card-body">
              <h5 class="card-title">30 à 40 ans</h5>
              <div class="text text-center">
              <%= form.radio_button :age, 30 %>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card">
            <img src="<%= image_path("40.jpeg") %>" class="card-img" alt="...">
            <div class="card-body">
              <h5 class="card-title">40 à 50 ans</h5>
              <div class="text text-center">
                <%= form.radio_button :age, 40 %>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card">
            <img src="<%= image_path("50.jpeg") %>" class="card-img" alt="...">
            <div class="card-body">
              <h5 class="card-title">50 à 60 ans</h5>
              <div class="text text-center">
                <%= form.radio_button :age, 50 %>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
  <div class="card-footer bg-transparent border-success text-center">
    <%= form.submit "Rechercher" %>
  </div>
</div>
    <%end %>

LaBonneFemme/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaBonneFemme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-light" style="background-color: #fec5d9;">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <button type="button" class="btn btn-link color-99206B">
          <a class="py-2" href="<%= root_path %>" style><h3>LaBonneFemme</h3></a>
        </button>
        <a class="py-2 d-none d-md-inline-block" href="<%= new_woman_path %>">Déposer une annonce</a>
        <a class="py-2 d-none d-md-inline-block" href="<%= women_path %>">parcourir les annonces</a>
      </div>
    </nav>
  <br><br>
    <%= yield %>
  </body>
</html>

LaBonneFemme/app/views/women/create.html.erb
<h1>Women#create</h1>
<p>Find me in app/views/women/create.html.erb</p>

LaBonneFemme/app/views/women/index.html.erb
<%= render 'print_announces', locals: { women: @women} %>

LaBonneFemme/app/views/women/new.html.erb
<!--   <% if @woman.invalid? %>
  <div class="alert alert-danger">
    <% @woman.errors.full_messages.each do |message| %>
      <%= message%>
    <%end %>

  </div>
  <%end %>  -->



<%= form_with model: @woman, local: true do |form| %>

  <div class="card border-success mb-6" style="max-width: 40%;margin-left: 30%">
    <div class="card-header bg-transparent border-success text-center" style="border-color :#fec5d9">Soyez créatif</div>
    <div class="card-body text-success">
  <p>
    <%= form.label :name, "prenom : " %>
    <%= form.text_field :name %>

  </p>
  <p>
    <%= form.label :surname, "nom de famille : " %>
    <%= form.text_field :surname %>

  </p>
  <p>
    <%= form.label :age, "age : " %>
    <%= form.number_field :age %>
  </p>

  <p>
    <%= form.label :NumberPhone, "Numéro de portable : " %>
    <%= form.telephone_field :NumberPhone %>
  </p>

  <p>
    <%= form.label :color_eyes, "couleur des yeux : " %>
    <%= form.select :color_eyes, ["bleus", "marrons", "noirs", "verts"] %>
  </p>

  <p>
    <%= form.label :color_hair, "couleur des cheveux :" %>
    <%= form.select :color_hair, ["rousse", "blonde", "chataigne", "brune"] %>
  </p>

  <p>
    <%= form.label :description, "petite description : " %>
    <%= form.text_area :description, size: "50x2" %>
  </p>



      <div class="card-footer bg-transparent border-success text-center">
         <%= form.submit "publier l'annonce" %>
      </div>

<%end %>
</div>
</div>

LaBonneFemme/app/views/women/search.html.erb
<%= render 'print_announces', locals: { women_sort: @women} %>

LaBonneFemme/app/views/women/show.html.erb
<h1>Women#show</h1>
<div>prenom : <%= @woman.name %></div>